spring:
  application:
    name: quiz-application-service
  datasource:
    url: jdbc:mysql://localhost:3306/quizzes?createDatabaseIfNotExist=true
    username: root
    password: 12345
  redis:
    host: localhost
    port: 6379
  server:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true